# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20170602_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
    ]
