# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_test_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
