# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='q_answers',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='T_question',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='a_num',
        ),
        migrations.AddField(
            model_name='test',
            name='a_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='q_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
