# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20170610_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='test',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
