# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_questions_answer_r'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['pk']},
        ),
    ]
