# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_test_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['pk'], 'permissions': (('can_delete', 'Can delete existing tests'),)},
        ),
    ]
