# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_mistakes_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistakes',
            name='answer',
        ),
        migrations.AddField(
            model_name='mistakes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Questions'),
            preserve_default=False,
        ),
    ]
